### ISSUE TITLE
Accessing the tackle operator in EKS

### ISSUE THREAD

**Issue by Murali-Cloudbridge** [konveyor/tackle2-operator#167] opened 2023-03-22 20:27 UTC
I have installed the latest version of tackle but not some pods are in a pending state.

`NAMESPACE            NAME                                                              READY   STATUS      RESTARTS   AGE
default              nginx-deployment-7fb96c846b-cvf4t                                 1/1     Running     0          5h42m
default              nginx-deployment-7fb96c846b-nhp6d                                 1/1     Running     0          5h42m
default              nginx-deployment-7fb96c846b-wbx9h                                 1/1     Running     0          5h42m
konveyor-tackle      konveyor-tackle-wr9w2                                             1/1     Running     0          5h28m
kube-system          aws-node-9nqp7                                                    1/1     Running     0          6h51m
kube-system          aws-node-tsmq4                                                    1/1     Running     0          6h51m
kube-system          cluster-autoscaler-7d58d9969d-75mtf                               1/1     Running     0          4h26m
kube-system          coredns-7cf95b74cc-hdk2z                                          1/1     Running     0          6h57m
kube-system          coredns-7cf95b74cc-x6twf                                          1/1     Running     0          6h57m
kube-system          kube-proxy-t5h5m                                                  1/1     Running     0          6h51m
kube-system          kube-proxy-xx8vj                                                  1/1     Running     0          6h51m
my-tackle-operator   tackle-keycloak-postgresql-f455ffdf8-b5qn9                        0/1     Pending     0          5h19m
my-tackle-operator   tackle-operator-7fc8bd6bb7-87ks7                                  1/1     Running     0          5h18m
olm                  a42881ea1507f1361d60825127fbe483b60b751c575a69ef734fcd24e6ctlfq   0/1     Completed   0          6h20m
olm                  catalog-operator-655fb46cd4-5jnkb                                 1/1     Running     0          6h22m
olm                  olm-operator-67fdb4b99d-txv6c                                     1/1     Running     0          6h22m
olm                  packageserver-5f55f478ff-s2fv4                                    1/1     Running     0          6h21m
muralithimmegowda@CB-L015 ~ % 

tackle-keycloak-postgresql : It has no events or errors but is in a pending state. 

It says succeeded. I have installed this in the latest version of EKS 1.25. 
muralithimmegowda@CB-L015 ~ % kubectl get csv -n my-tackle-operator
NAME                     DISPLAY           VERSION   REPLACES                 PHASE
tackle-operator.v2.1.3   Tackle Operator   2.1.3     tackle-operator.v2.1.2   Succeeded
muralithimmegowda@CB-L015 ~ % 

It has not created any ingress how to access the application. Please suggest.

**Comment by Murali-Cloudbridge** [comment] 2023-03-22 21:22
I installed ingress as well since it was pre-requisite.

nginx-ingress        nginx-ingress                NodePort    172.20.206.25    <none>        80:31475/TCP,443:32118/TCP   88s

**Comment by Murali-Cloudbridge** [comment] 2023-03-22 21:57
![image](https://user-images.githubusercontent.com/71437488/227047808-e5f69bc7-6c53-4619-9016-adf1cae90c58.png)

**Comment by Murali-Cloudbridge** [comment] 2023-03-22 21:59
![image](https://user-images.githubusercontent.com/71437488/227048069-3c6af32b-2cc7-4dc3-967b-fd5bef846241.png)

**Comment by Murali-Cloudbridge** [comment] 2023-03-23 14:45
![image](https://user-images.githubusercontent.com/71437488/227239727-683216b6-207d-46dc-aa88-a941763b0b6e.png)
![image](https://user-images.githubusercontent.com/71437488/227239823-3aee8f10-df40-4cae-9153-da046f59e7ca.png)

Trying to install even older versions of tackle v1.2 on different EKS cluster to check.

**Comment by Murali-Cloudbridge** [comment] 2023-03-24 11:06
Latest update: I could fix it myself by checking logs and fixing errors. I will prepare a doc for installing it on EKS. 

I can see the login page, but the credentials provided are not working.

admin / Passw0rd! 

![image](https://user-images.githubusercontent.com/71437488/227504343-1381b7ed-833a-4c3f-962a-eeb6066222c4.png)

Once I give creds, it displays the below page.

![image](https://user-images.githubusercontent.com/71437488/227504533-f1463b4d-9ccd-4b15-a397-45e0d9e7a3d8.png)

![image](https://user-images.githubusercontent.com/71437488/227505202-3710a33a-8b79-407f-9c19-35b8b857af8a.png)


I was able to see user admin created in logs.

![image](https://user-images.githubusercontent.com/71437488/227504652-5d33d679-43b3-4bb3-8def-01b63834a774.png)

Could you please suggest whether the creds are correct or to check anything different to check this issue.

**Comment by jwmatthews** [comment] 2023-03-29 10:58
From: https://github.com/konveyor/tackle2-operator/issues/169#issuecomment-1485854794
> Thanks a lot, John. I will try to modify the CR and check.
> 
> It will be great if I can access it via Ingress resource.
> 
> One more to report, once the tackle is installed keycloak pod was pending. It was due to pv was not bound. I had to install Addon in the EKS cluster - EBS-related drivers. I also got some permission issues, as shown below, the pod was crashingloopbackoff.
> 
> [mkdir: cannot create directory '/var/lib/pgsql/data/userdata': Permission denied
> 
> Then, I updated deployment yaml file and added below section in security context:
> 
> securitycontext: fsGroup: 2000 runAsNonRoot: true runAsUser: 1000
> 
> Then Issue was solved for keycloak pods and postgress.

@Murali-Cloudbridge wanted to thank you for sharing above, I am working through an EKS setup in off hours to learn more about this so we can get docs for EKS usage.   Have run into same issues as you

1. Need to configure the EBS-CSI addon for EKS as of k8s 1.23 the default has changed to ebs-csi opposed to in-tree, so ebs-csi AddOn is needed.    
Created some notes here for the EBS-CSI AddOn install for others:  https://gist.github.com/jwmatthews/d701da13eda5d57d4e8d2adf594fc4f2

3. tackle-pathfinder-postgresql in CrashLoopBackOff

```
tackle-pathfinder-postgresql-695b9798d6-pbq56                     0/1     CrashLoopBackOff   9 (2m21s ago)   11h

$ kubectl logs tackle-pathfinder-postgresql-695b9798d6-pbq56 -n konveyor-tackle
mkdir: cannot create directory '/var/lib/pgsql/data': Permission denied
```

I don't have much else to share just yet, but wanted to let you know I will continue to work through this so I can help to dig into the auth case and determine what we need to get Ingress working.

**Comment by jwmatthews** [comment] 2023-04-14 10:37
We have automation now for deploying EKS clusters for testing with ALB ingress configured.
https://github.com/konveyor/hack_env_helpers/tree/main/aws/eks

With pr #197 non-auth will be working if the tackle CR is created as:
```
kind: Tackle
apiVersion: tackle.konveyor.io/v1alpha1
metadata:
  name: tackle
  namespace: konveyor-tackle
spec:
  ui_ingress_class_name: alb
  ui_ingress_path_type: Prefix
```

Note that `rwx_supported` and `feature_auth_required` are now both set to `false` by default.

The last piece I need to test is the workflow when `feature_auth_required: true` is set.

**Comment by jwmatthews** [comment] 2023-04-17 20:57
The fix to https://github.com/konveyor/tackle2-operator/issues/167#issuecomment-1482627378 will be in https://github.com/konveyor/tackle2-ui/pull/822

The issue is we needed to add a few forwarding header parameters to our reverse proxy, without that it wasn't possible to use our auth workflow with `kubectl port-forward svc/tackle-ui 7080:8080 -n konveyor-tackle`

This issue didn't present itself when running on OpenShift clusters as when we accessed the UI via an OpenShift Route the header parameters were being added.

**Closed** 2023-04-26 10:29 UTC
